const WeatherActionTypes = {
    SET_WEATHER_DATA: 'SET_WEATHER_DATA',
    UPDATE_WEATHER_SUCCESS: 'UPDATE_CURRENT_WEATHER_SUCCESS',
    UPDATE_WEATHER_ERROR: 'UPDATE_CURRENT_WEATHER_ERROR',
}

export default WeatherActionTypes;
